// The wattage lookup table - the deterministic backbone of Ghost Watt.
//
// The vision model only does perception ("what's here, is it on?"). All energy
// reasoning happens here, against published-typical device power figures. Numbers
// are intentionally representative, not precise: the ranking of worst offenders
// is robust even when absolute watts are fuzzy, and the ranking is what drives action.

import type { DeviceCategory } from "./types";

export const DEVICE_CATALOG: DeviceCategory[] = [
  {
    id: "projector",
    label: "Projector",
    keywords: ["projector", "beamer", "data projector"],
    wattsOn: 250,
    wattsStandby: 5,
    dutyCycle: 1,
    icon: "projector",
    action: {
      label: "Auto-off timer linked to occupancy",
      type: "timer",
      cost: 40,
      savingsFraction: 0.95,
      note: "Projectors burn ~250 W and are routinely left running. A $40 timer or occupancy link kills overnight use.",
    },
  },
  {
    id: "smartboard",
    label: "Smartboard / interactive display",
    keywords: ["smartboard", "smart board", "interactive whiteboard", "interactive display", "promethean"],
    wattsOn: 150,
    wattsStandby: 8,
    dutyCycle: 1,
    icon: "tv",
    action: {
      label: "Master power strip + overnight off policy",
      type: "powerstrip",
      cost: 30,
      savingsFraction: 0.92,
      note: "Large interactive panels idle hot. A master strip cuts the whole board after hours.",
    },
  },
  {
    id: "tv",
    label: "TV / large display",
    keywords: ["television", "tv", "flat screen", "flatscreen", "monitor wall", "display screen"],
    wattsOn: 100,
    wattsStandby: 4,
    dutyCycle: 1,
    icon: "tv",
    action: {
      label: "Smart power strip with schedule",
      type: "powerstrip",
      cost: 30,
      savingsFraction: 0.93,
      note: "A scheduled smart strip blanks displays during empty hours.",
    },
  },
  {
    id: "monitor",
    label: "Computer monitor",
    keywords: ["monitor", "display", "screen"],
    wattsOn: 30,
    wattsStandby: 0.5,
    dutyCycle: 1,
    icon: "monitor",
    action: {
      label: "Smart power strips + auto-sleep policy",
      type: "powerstrip",
      cost: 60,
      savingsFraction: 0.95,
      note: "Monitors left on overnight are the classic lab phantom load. Strips + sleep recover almost all of it.",
    },
  },
  {
    id: "desktop",
    label: "Desktop computer",
    keywords: ["desktop", "computer tower", "pc tower", "workstation", "tower", "desktop computer", "computer"],
    wattsOn: 80,
    wattsStandby: 3,
    dutyCycle: 1,
    icon: "desktop",
    action: {
      label: "Enable sleep + scheduled overnight shutdown",
      type: "policy",
      cost: 0,
      savingsFraction: 0.9,
      note: "Group-policy sleep and Wake-on-LAN patching means machines can power down nightly for free.",
    },
  },
  {
    id: "laptop",
    label: "Laptop / Chromebook (charging)",
    keywords: ["laptop", "notebook", "chromebook", "macbook"],
    wattsOn: 30,
    wattsStandby: 2,
    dutyCycle: 1,
    icon: "laptop",
    action: {
      label: "Charging-cart timer",
      type: "timer",
      cost: 20,
      savingsFraction: 0.8,
      note: "Charging carts trickle power all night. A timer charges them, then cuts off.",
    },
  },
  {
    id: "ceiling_light",
    label: "Overhead lighting",
    keywords: [
      "ceiling light",
      "overhead light",
      "fluorescent",
      "light fixture",
      "lighting",
      "hallway light",
      "high bay",
      "ceiling lights",
      "lights",
      "light",
      "lamp",
    ],
    wattsOn: 120,
    wattsStandby: 0,
    dutyCycle: 1,
    icon: "light",
    action: {
      label: "Occupancy / motion sensors",
      type: "occupancy",
      cost: 50,
      savingsFraction: 0.9,
      note: "Motion sensors switch banks off minutes after a room empties - the single highest-yield retrofit for hallways.",
    },
  },
  {
    id: "vending_cold",
    label: "Refrigerated vending machine",
    keywords: ["vending machine", "vending", "soda machine", "drink machine", "snack machine"],
    wattsOn: 400,
    wattsStandby: 400,
    dutyCycle: 0.55,
    thermostatic: true,
    icon: "vending",
    action: {
      label: "Occupancy-based vending controller",
      type: "occupancy",
      cost: 180,
      savingsFraction: 0.5,
      note: "A vending occupancy sensor powers down lighting/cooling when nobody's around, cutting ~half the load.",
    },
  },
  {
    id: "fridge",
    label: "Refrigerator / mini-fridge",
    keywords: ["refrigerator", "fridge", "mini fridge", "freezer", "cooler"],
    wattsOn: 100,
    wattsStandby: 100,
    dutyCycle: 0.4,
    thermostatic: true,
    icon: "fridge",
    action: {
      label: "Consolidate & unplug surplus units",
      type: "consolidate",
      cost: 0,
      savingsFraction: 0.3,
      note: "Schools accumulate personal mini-fridges. Consolidating to shared units removes redundant cooling.",
    },
  },
  {
    id: "water_cooler",
    label: "Water cooler / dispenser",
    keywords: ["water cooler", "water dispenser", "hot and cold dispenser"],
    wattsOn: 90,
    wattsStandby: 90,
    dutyCycle: 0.5,
    thermostatic: true,
    icon: "water",
    action: {
      label: "Timer switch on the hot tank",
      type: "timer",
      cost: 20,
      savingsFraction: 0.6,
      note: "The hot tank reheats all night for nobody. A timer disables it after hours.",
    },
  },
  {
    id: "copier",
    label: "Copier / large MFP",
    keywords: ["copier", "copy machine", "multifunction", "mfp", "photocopier"],
    wattsOn: 120,
    wattsStandby: 15,
    dutyCycle: 1,
    icon: "printer",
    action: {
      label: "Enable deep-sleep + overnight off",
      type: "policy",
      cost: 0,
      savingsFraction: 0.8,
      note: "Most copiers ship with deep-sleep disabled. Turning it on is free.",
    },
  },
  {
    id: "printer",
    label: "Printer",
    keywords: ["printer", "laser printer", "inkjet"],
    wattsOn: 40,
    wattsStandby: 5,
    dutyCycle: 1,
    icon: "printer",
    action: {
      label: "Enable deep-sleep + overnight off",
      type: "policy",
      cost: 0,
      savingsFraction: 0.8,
      note: "Idle printers hold heaters warm. Deep-sleep settings remove most of it for free.",
    },
  },
  {
    id: "server",
    label: "Server / network rack",
    keywords: ["server", "network rack", "network closet", "switch", "rack"],
    wattsOn: 200,
    wattsStandby: 200,
    dutyCycle: 1,
    thermostatic: true,
    icon: "server",
    action: {
      label: "Right-size & virtualize (keep critical up)",
      type: "consolidate",
      cost: 0,
      savingsFraction: 0.2,
      note: "Some racks run idle legacy boxes 24/7. Audit and virtualize the non-critical ones.",
    },
  },
  {
    id: "ac_window",
    label: "Window / portable AC",
    keywords: ["air conditioner", "ac unit", "window unit", "window ac", "portable ac"],
    wattsOn: 900,
    wattsStandby: 900,
    dutyCycle: 0.5,
    thermostatic: true,
    icon: "ac",
    action: {
      label: "Programmable thermostat with setback",
      type: "thermostat",
      cost: 60,
      savingsFraction: 0.6,
      note: "A setback schedule stops cooling empty rooms overnight and on weekends.",
    },
  },
  {
    id: "space_heater",
    label: "Space heater",
    keywords: ["space heater", "portable heater", "electric heater"],
    wattsOn: 1200,
    wattsStandby: 1200,
    dutyCycle: 0.5,
    thermostatic: true,
    icon: "heater",
    action: {
      label: "Remove / put on a smart plug",
      type: "remove",
      cost: 25,
      savingsFraction: 0.8,
      note: "A single forgotten space heater can outweigh a whole lab. A smart plug guarantees it's off after hours.",
    },
  },
  {
    id: "coffee",
    label: "Coffee maker / kettle (warming)",
    keywords: ["coffee maker", "coffee machine", "kettle", "hot plate"],
    wattsOn: 100,
    wattsStandby: 2,
    dutyCycle: 0.3,
    icon: "coffee",
    action: {
      label: "Auto-off or smart plug",
      type: "remove",
      cost: 0,
      savingsFraction: 0.8,
      note: "Warming plates left on draw power for nobody. Auto-off models or a smart plug fix it.",
    },
  },
  {
    id: "microwave",
    label: "Microwave (standby clock)",
    keywords: ["microwave"],
    wattsOn: 3,
    wattsStandby: 3,
    dutyCycle: 1,
    icon: "microwave",
    action: {
      label: "Unplug after hours",
      type: "remove",
      cost: 0,
      savingsFraction: 0.9,
      note: "Small per-unit, but the clock display runs 24/7. Trivial to cut.",
    },
  },
];

export const CATALOG_BY_ID = Object.fromEntries(DEVICE_CATALOG.map((c) => [c.id, c]));

/** Number words the parser understands when counting devices. */
export const NUMBER_WORDS: Record<string, number> = {
  a: 1, an: 1, one: 1, two: 2, three: 3, four: 4, five: 5, six: 6, seven: 7,
  eight: 8, nine: 9, ten: 10, eleven: 11, twelve: 12, dozen: 12, fifteen: 15,
  twenty: 20, thirty: 30, forty: 40, fifty: 50,
};
