// Catalog expansion: everything beyond a classroom.
//
// The original catalog covered a school day - screens, lights, the vending machine.
// But phantom load in real buildings is dominated by things nobody photographs on a
// classroom walk: the rooftop unit cycling over an empty gym, the walk-in cooler in
// the cafeteria, the pool pump, the parking-lot lights on a photocell that failed
// years ago. These entries extend Ghost Watt to offices, kitchens, workshops,
// clinics, gyms and homes.
//
// Wattage figures are representative published values for the device class, with a
// low/high band so the app can show a range rather than pretending to a precision
// it does not have. Keywords are deliberately specific: these are matched before
// the generic core entries, so a broad keyword here would swallow everything.

import type { DeviceCategory } from "./types";

export const EXTRA_DEVICES: DeviceCategory[] = [
  // ---- heating, cooling, ventilation ------------------------------------
  {
    id: "rtu",
    label: "Rooftop HVAC unit",
    keywords: ["rooftop unit", "rtu", "air handler", "hvac unit", "packaged unit"],
    wattsOn: 3500,
    wattsStandby: 300,
    wattsLow: 1500,
    wattsHigh: 7000,
    dutyCycle: 0.45,
    thermostatic: true,
    group: "hvac",
    source: "Typical 5-10 ton commercial packaged unit under part load.",
    icon: "ac",
    action: {
      label: "Night setback + optimal start scheduling",
      type: "thermostat",
      cost: 120,
      savingsFraction: 0.55,
      note: "Conditioning an empty building is the single largest after-hours load in most schools. A setback schedule is the highest-value control change available.",
    },
  },
  {
    id: "heat_pump",
    label: "Mini-split / heat pump",
    keywords: ["mini split", "mini-split", "heat pump", "ductless"],
    wattsOn: 1200,
    wattsStandby: 15,
    wattsLow: 600,
    wattsHigh: 2400,
    dutyCycle: 0.45,
    thermostatic: true,
    group: "hvac",
    source: "Typical single-zone residential/light-commercial mini-split.",
    icon: "ac",
    action: {
      label: "Schedule setback on the zone controller",
      type: "thermostat",
      cost: 60,
      savingsFraction: 0.5,
      note: "Zone units are routinely left at occupied setpoints all weekend.",
    },
  },
  {
    id: "exhaust_fan",
    label: "Exhaust / ventilation fan",
    keywords: ["exhaust fan", "ventilation fan", "extractor fan", "roof fan"],
    wattsOn: 300,
    wattsStandby: 0,
    wattsLow: 90,
    wattsHigh: 800,
    dutyCycle: 1,
    group: "hvac",
    source: "Typical commercial inline/roof exhaust fan.",
    icon: "ac",
    action: {
      label: "Interlock with occupancy or the HVAC schedule",
      type: "occupancy",
      cost: 80,
      savingsFraction: 0.7,
      note: "Exhaust fans are often hard-wired on and run 8,760 hours a year for no reason.",
    },
  },
  {
    id: "dehumidifier",
    label: "Dehumidifier",
    keywords: ["dehumidifier", "humidity control"],
    wattsOn: 500,
    wattsStandby: 3,
    wattsLow: 300,
    wattsHigh: 800,
    dutyCycle: 0.5,
    thermostatic: true,
    group: "hvac",
    source: "Typical 50-70 pint commercial dehumidifier.",
    icon: "ac",
    action: {
      label: "Humidistat setpoint review",
      type: "thermostat",
      cost: 40,
      savingsFraction: 0.4,
      note: "Frequently left at an unnecessarily low setpoint, running far more than required.",
    },
  },
  {
    id: "air_purifier",
    label: "Air purifier",
    keywords: ["air purifier", "hepa unit", "air cleaner", "air scrubber"],
    wattsOn: 55,
    wattsStandby: 2,
    wattsLow: 20,
    wattsHigh: 120,
    dutyCycle: 1,
    group: "hvac",
    source: "Typical classroom-sized HEPA unit on medium.",
    icon: "ac",
    action: {
      label: "Drop to low or off when unoccupied",
      type: "policy",
      cost: 0,
      savingsFraction: 0.7,
      note: "Purifiers bought during the pandemic often still run at full speed around the clock.",
    },
  },
  {
    id: "circulator_pump",
    label: "Boiler / circulator pump",
    keywords: ["circulator pump", "boiler pump", "circulation pump", "hydronic pump"],
    wattsOn: 250,
    wattsStandby: 0,
    wattsLow: 80,
    wattsHigh: 750,
    dutyCycle: 0.8,
    group: "hvac",
    source: "Typical hydronic heating circulator.",
    icon: "heater",
    action: {
      label: "Fit a variable-speed circulator",
      type: "thermostat",
      cost: 400,
      savingsFraction: 0.6,
      note: "Constant-speed circulators run flat out year-round. Variable-speed replacements cut most of that.",
    },
  },

  // ---- lighting ---------------------------------------------------------
  {
    id: "exterior_light",
    label: "Exterior / parking-lot lighting",
    keywords: ["parking lot light", "exterior light", "flood light", "floodlight", "pole light", "security light", "outdoor light"],
    wattsOn: 250,
    wattsStandby: 0,
    wattsLow: 60,
    wattsHigh: 400,
    dutyCycle: 1,
    group: "lighting",
    source: "Typical pole-mounted HID or LED area fixture.",
    icon: "light",
    action: {
      label: "Photocell + timeclock repair, LED retrofit",
      type: "timer",
      cost: 150,
      savingsFraction: 0.6,
      note: "Failed photocells leave lot lighting burning through daylight. Cheap to check, expensive to ignore.",
    },
  },
  {
    id: "exit_sign",
    label: "Illuminated exit sign",
    keywords: ["exit sign", "emergency light", "emergency sign"],
    wattsOn: 5,
    wattsStandby: 5,
    wattsLow: 1,
    wattsHigh: 40,
    dutyCycle: 1,
    thermostatic: true,
    group: "lighting",
    source: "Incandescent exit signs draw ~40 W; LED replacements ~1-5 W.",
    icon: "light",
    action: {
      label: "Retrofit any remaining incandescent signs to LED",
      type: "remove",
      cost: 25,
      savingsFraction: 0.85,
      note: "Legally required to run 24/7, which is exactly why the old ones are worth replacing.",
    },
  },
  {
    id: "stage_light",
    label: "Stage / auditorium lighting",
    keywords: ["stage light", "stage lighting", "theatre light", "theater light", "spotlight", "par can"],
    wattsOn: 750,
    wattsStandby: 20,
    wattsLow: 200,
    wattsHigh: 2000,
    dutyCycle: 1,
    group: "lighting",
    source: "Conventional tungsten fixture; LED equivalents draw far less.",
    icon: "light",
    action: {
      label: "Kill dimmer-rack standby, LED retrofit",
      type: "powerstrip",
      cost: 200,
      savingsFraction: 0.8,
      note: "Dimmer racks idle warm even with every channel down. Auditoriums sit empty most of the year.",
    },
  },

  // ---- refrigeration & kitchen -----------------------------------------
  {
    id: "walk_in_cooler",
    label: "Walk-in cooler / freezer",
    keywords: ["walk-in cooler", "walk in cooler", "walk-in freezer", "walk in freezer", "cold room"],
    wattsOn: 2000,
    wattsStandby: 2000,
    wattsLow: 900,
    wattsHigh: 4000,
    dutyCycle: 0.6,
    thermostatic: true,
    group: "refrigeration",
    source: "Typical cafeteria walk-in with compressor and evaporator fans.",
    icon: "fridge",
    action: {
      label: "Door-gasket repair, strip curtains, EC fan motors",
      type: "consolidate",
      cost: 350,
      savingsFraction: 0.3,
      note: "Failing gaskets and shaded-pole evaporator fans quietly add thousands a year in a school kitchen.",
    },
  },
  {
    id: "reach_in_cooler",
    label: "Reach-in / display cooler",
    keywords: ["reach-in cooler", "reach in cooler", "display cooler", "glass door cooler", "merchandiser"],
    wattsOn: 550,
    wattsStandby: 550,
    wattsLow: 250,
    wattsHigh: 900,
    dutyCycle: 0.55,
    thermostatic: true,
    group: "refrigeration",
    source: "Typical glass-door commercial merchandiser.",
    icon: "fridge",
    action: {
      label: "Night covers and anti-sweat heater controls",
      type: "occupancy",
      cost: 120,
      savingsFraction: 0.35,
      note: "Anti-sweat door heaters run constantly unless a humidity controller is fitted.",
    },
  },
  {
    id: "ice_machine",
    label: "Ice machine",
    keywords: ["ice machine", "ice maker"],
    wattsOn: 800,
    wattsStandby: 100,
    wattsLow: 350,
    wattsHigh: 1500,
    dutyCycle: 0.4,
    thermostatic: true,
    group: "refrigeration",
    source: "Typical modular commercial ice maker with bin.",
    icon: "fridge",
    action: {
      label: "Shut down over holidays and long breaks",
      type: "policy",
      cost: 0,
      savingsFraction: 0.35,
      note: "Ice machines keep making and re-freezing melt for an empty building through every school holiday.",
    },
  },
  {
    id: "steam_table",
    label: "Steam table / food warmer",
    keywords: ["steam table", "food warmer", "warming cabinet", "holding cabinet", "bain marie"],
    wattsOn: 1500,
    wattsStandby: 400,
    wattsLow: 700,
    wattsHigh: 3000,
    dutyCycle: 0.7,
    group: "kitchen",
    source: "Typical multi-well electric steam table.",
    icon: "heater",
    action: {
      label: "Start-up timer instead of preheating at 6am",
      type: "timer",
      cost: 60,
      savingsFraction: 0.5,
      note: "Warming equipment is routinely switched on hours before service and left on after it.",
    },
  },
  {
    id: "commercial_oven",
    label: "Commercial oven / range",
    keywords: ["commercial oven", "convection oven", "combi oven", "range top", "griddle"],
    wattsOn: 6000,
    wattsStandby: 800,
    wattsLow: 3000,
    wattsHigh: 12000,
    dutyCycle: 0.35,
    group: "kitchen",
    source: "Typical electric convection oven under intermittent load.",
    icon: "heater",
    action: {
      label: "Staggered start-up and end-of-service shutdown checklist",
      type: "policy",
      cost: 0,
      savingsFraction: 0.4,
      note: "Idle ovens held at temperature between services are the biggest single kitchen waste.",
    },
  },
  {
    id: "dishwasher_commercial",
    label: "Commercial dishwasher",
    keywords: ["commercial dishwasher", "dish machine", "warewasher", "hobart"],
    wattsOn: 2500,
    wattsStandby: 900,
    wattsLow: 1200,
    wattsHigh: 5000,
    dutyCycle: 0.3,
    group: "kitchen",
    source: "Door-type machine with an electric booster heater.",
    icon: "water",
    action: {
      label: "Turn off the booster heater outside service hours",
      type: "policy",
      cost: 0,
      savingsFraction: 0.6,
      note: "The booster heater holds 180F water all day and night unless someone switches it off.",
    },
  },
  {
    id: "coffee_urn",
    label: "Coffee urn / hot water boiler",
    keywords: ["coffee urn", "hot water boiler", "water boiler", "instant hot water", "hot water dispenser"],
    wattsOn: 1500,
    wattsStandby: 250,
    wattsLow: 800,
    wattsHigh: 3000,
    dutyCycle: 0.4,
    thermostatic: true,
    group: "kitchen",
    source: "Typical plumbed-in hot water boiler holding temperature.",
    icon: "coffee",
    action: {
      label: "Timer switch matched to occupancy",
      type: "timer",
      cost: 30,
      savingsFraction: 0.65,
      note: "Holding a tank at boiling point overnight is pure loss.",
    },
  },

  // ---- network, servers, security ---------------------------------------
  {
    id: "ups",
    label: "UPS / battery backup",
    keywords: ["ups", "battery backup", "uninterruptible"],
    wattsOn: 120,
    wattsStandby: 120,
    wattsLow: 30,
    wattsHigh: 400,
    dutyCycle: 1,
    thermostatic: true,
    group: "network",
    source: "Conversion and float-charging losses on a small rack UPS.",
    icon: "server",
    action: {
      label: "Right-size or retire over-specified units",
      type: "consolidate",
      cost: 0,
      savingsFraction: 0.25,
      note: "A UPS sized for equipment that was decommissioned years ago still burns conversion losses 24/7.",
    },
  },
  {
    id: "access_point",
    label: "Wi-Fi access point",
    keywords: ["access point", "wifi ap", "wireless access point", "wap"],
    wattsOn: 15,
    wattsStandby: 12,
    wattsLow: 6,
    wattsHigh: 30,
    dutyCycle: 1,
    thermostatic: true,
    group: "network",
    source: "Typical PoE 802.11ax access point including PoE losses.",
    icon: "server",
    action: {
      label: "Schedule PoE ports off overnight where policy allows",
      type: "policy",
      cost: 0,
      savingsFraction: 0.3,
      note: "Small individually, but a large campus runs hundreds of them continuously.",
    },
  },
  {
    id: "security_recorder",
    label: "Security recorder / NVR",
    keywords: ["nvr", "dvr", "security recorder", "cctv recorder", "camera server"],
    wattsOn: 90,
    wattsStandby: 90,
    wattsLow: 40,
    wattsHigh: 250,
    dutyCycle: 1,
    thermostatic: true,
    group: "network",
    source: "Typical multi-channel network video recorder with drives.",
    icon: "server",
    action: {
      label: "Consolidate recorders and retire duplicates",
      type: "consolidate",
      cost: 0,
      savingsFraction: 0.2,
      note: "Necessary equipment, but sites often run several part-full recorders where one would do.",
    },
  },
  {
    id: "pa_amplifier",
    label: "PA / audio amplifier",
    keywords: ["pa system", "public address", "amplifier", "audio rack", "bell system"],
    wattsOn: 120,
    wattsStandby: 45,
    wattsLow: 30,
    wattsHigh: 400,
    dutyCycle: 1,
    group: "network",
    source: "Rack amplifier idling between announcements.",
    icon: "server",
    action: {
      label: "Auto-standby amplifiers or schedule the rack",
      type: "powerstrip",
      cost: 50,
      savingsFraction: 0.5,
      note: "Amplifiers idle at a large fraction of rated draw waiting for a bell that rings six times a day.",
    },
  },

  // ---- displays & signage -----------------------------------------------
  {
    id: "digital_signage",
    label: "Digital signage / info display",
    keywords: ["digital sign", "digital signage", "information display", "menu board", "video wall"],
    wattsOn: 120,
    wattsStandby: 5,
    wattsLow: 50,
    wattsHigh: 350,
    dutyCycle: 1,
    group: "display",
    source: "Commercial-grade display running at signage brightness.",
    icon: "tv",
    action: {
      label: "Schedule blanking outside opening hours",
      type: "timer",
      cost: 0,
      savingsFraction: 0.7,
      note: "Most commercial displays have a built-in scheduler that nobody has ever opened.",
    },
  },
  {
    id: "scoreboard",
    label: "Scoreboard / LED sign",
    keywords: ["scoreboard", "led sign", "marquee", "message board"],
    wattsOn: 400,
    wattsStandby: 30,
    wattsLow: 100,
    wattsHigh: 1500,
    dutyCycle: 1,
    group: "display",
    source: "Typical gymnasium scoreboard or outdoor LED marquee.",
    icon: "tv",
    action: {
      label: "Dimming schedule and overnight off",
      type: "timer",
      cost: 60,
      savingsFraction: 0.6,
      note: "Outdoor signs run at daylight brightness all night unless a dimming schedule is set.",
    },
  },

  // ---- specialty, shop, lab, leisure ------------------------------------
  {
    id: "pool_pump",
    label: "Pool pump / filtration",
    keywords: ["pool pump", "pool filter", "filtration pump", "swimming pool"],
    wattsOn: 1800,
    wattsStandby: 0,
    wattsLow: 750,
    wattsHigh: 3000,
    dutyCycle: 0.9,
    group: "specialty",
    source: "Single-speed commercial pool circulation pump.",
    icon: "water",
    action: {
      label: "Variable-speed pump and reduced turnover schedule",
      type: "thermostat",
      cost: 900,
      savingsFraction: 0.65,
      note: "Halving pump speed cuts power by roughly eight times. The best-paying retrofit any pool has.",
    },
  },
  {
    id: "hand_dryer",
    label: "Hand dryer",
    keywords: ["hand dryer", "hand-dryer", "air dryer"],
    wattsOn: 1400,
    wattsStandby: 3,
    wattsLow: 500,
    wattsHigh: 2300,
    dutyCycle: 0.02,
    group: "specialty",
    source: "High-speed dryer; duty cycle is tiny but standby is continuous.",
    icon: "heater",
    action: {
      label: "Disable the heating element",
      type: "policy",
      cost: 0,
      savingsFraction: 0.6,
      note: "Most dryers dry by air speed, not heat. The element is often a switch inside the cover.",
    },
  },
  {
    id: "ev_charger",
    label: "EV charging station",
    keywords: ["ev charger", "car charger", "charging station", "level 2 charger"],
    wattsOn: 7000,
    wattsStandby: 15,
    wattsLow: 3300,
    wattsHigh: 19000,
    dutyCycle: 0.15,
    group: "specialty",
    source: "Level 2 charger; standby draw is small but demand charges are not.",
    icon: "ac",
    action: {
      label: "Shift charging off the demand peak",
      type: "timer",
      cost: 0,
      savingsFraction: 0.25,
      note: "The energy is wanted; the peak-demand charge it creates is not. Scheduling moves it cheaply.",
    },
  },
  {
    id: "kiln",
    label: "Kiln / heat treatment",
    keywords: ["kiln", "pottery kiln", "furnace oven"],
    wattsOn: 8000,
    wattsStandby: 20,
    wattsLow: 2000,
    wattsHigh: 12000,
    dutyCycle: 0.5,
    group: "specialty",
    source: "Typical electric school art kiln during a firing cycle.",
    icon: "heater",
    action: {
      label: "Fire overnight on off-peak rates, confirm shutdown",
      type: "policy",
      cost: 0,
      savingsFraction: 0.3,
      note: "Kilns are enormous intermittent loads. Timing the firing matters more than the firing itself.",
    },
  },
  {
    id: "printer_3d",
    label: "3D printer",
    keywords: ["3d printer", "3-d printer", "additive printer"],
    wattsOn: 120,
    wattsStandby: 8,
    wattsLow: 50,
    wattsHigh: 350,
    dutyCycle: 0.6,
    group: "specialty",
    source: "Desktop FDM printer with a heated bed.",
    icon: "printer",
    action: {
      label: "Smart plug with a print-complete cutoff",
      type: "powerstrip",
      cost: 25,
      savingsFraction: 0.7,
      note: "Heated beds and idle hot ends stay powered for hours after a print finishes.",
    },
  },
  {
    id: "aquarium",
    label: "Aquarium / terrarium",
    keywords: ["aquarium", "fish tank", "terrarium", "vivarium"],
    wattsOn: 150,
    wattsStandby: 150,
    wattsLow: 40,
    wattsHigh: 400,
    dutyCycle: 0.6,
    thermostatic: true,
    group: "specialty",
    source: "Classroom tank with heater, pump and lighting.",
    icon: "water",
    action: {
      label: "Timer the lighting, insulate the tank",
      type: "timer",
      cost: 25,
      savingsFraction: 0.3,
      note: "The livestock needs the heater. The lights do not need to be on at 3am.",
    },
  },
  {
    id: "grow_light",
    label: "Grow light / greenhouse lighting",
    keywords: ["grow light", "greenhouse light", "plant light", "horticultural light"],
    wattsOn: 400,
    wattsStandby: 0,
    wattsLow: 100,
    wattsHigh: 1000,
    dutyCycle: 1,
    group: "specialty",
    source: "Typical HID or LED horticultural fixture.",
    icon: "light",
    action: {
      label: "Photoperiod timer",
      type: "timer",
      cost: 30,
      savingsFraction: 0.4,
      note: "Plants need a dark period. Timers are cheap and often simply missing.",
    },
  },
  {
    id: "air_compressor",
    label: "Air compressor",
    keywords: ["air compressor", "shop compressor", "compressed air"],
    wattsOn: 2200,
    wattsStandby: 60,
    wattsLow: 750,
    wattsHigh: 7500,
    dutyCycle: 0.3,
    group: "specialty",
    source: "Shop compressor cycling to hold tank pressure.",
    icon: "ac",
    action: {
      label: "Fix leaks and isolate the receiver after hours",
      type: "policy",
      cost: 0,
      savingsFraction: 0.6,
      note: "A leaking compressed-air system cycles all night to pressurise an empty workshop.",
    },
  },
  {
    id: "lab_equipment",
    label: "Lab incubator / autoclave",
    keywords: ["incubator", "autoclave", "centrifuge", "fume hood", "laboratory oven"],
    wattsOn: 700,
    wattsStandby: 200,
    wattsLow: 200,
    wattsHigh: 2500,
    dutyCycle: 0.6,
    thermostatic: true,
    group: "specialty",
    source: "Typical benchtop lab equipment held at temperature.",
    icon: "heater",
    action: {
      label: "Shut down non-critical units outside term time",
      type: "policy",
      cost: 0,
      savingsFraction: 0.4,
      note: "Some of this genuinely must stay on. Much of it is held hot out of habit.",
    },
  },
  {
    id: "cardio_machine",
    label: "Treadmill / cardio machine",
    keywords: ["treadmill", "elliptical", "exercise bike", "cardio machine", "rowing machine"],
    wattsOn: 700,
    wattsStandby: 8,
    wattsLow: 300,
    wattsHigh: 1500,
    dutyCycle: 0.2,
    group: "specialty",
    source: "Motorised treadmill; console standby is continuous.",
    icon: "desktop",
    action: {
      label: "Master switch for the equipment row",
      type: "powerstrip",
      cost: 45,
      savingsFraction: 0.8,
      note: "Twenty consoles idling in a closed gym add up to a constant background load.",
    },
  },
  {
    id: "washer_dryer",
    label: "Washing machine / tumble dryer",
    keywords: ["washing machine", "tumble dryer", "clothes dryer", "laundry machine"],
    wattsOn: 2500,
    wattsStandby: 5,
    wattsLow: 500,
    wattsHigh: 5000,
    dutyCycle: 0.2,
    group: "specialty",
    source: "Electric dryer dominates; washer draw is much lower.",
    icon: "water",
    action: {
      label: "Run full loads on off-peak hours",
      type: "policy",
      cost: 0,
      savingsFraction: 0.25,
      note: "Athletics departments run laundry constantly. Timing and load size are the levers.",
    },
  },
  {
    id: "sump_pump",
    label: "Sump / booster pump",
    keywords: ["sump pump", "booster pump", "water pump", "well pump"],
    wattsOn: 800,
    wattsStandby: 5,
    wattsLow: 250,
    wattsHigh: 2000,
    dutyCycle: 0.25,
    group: "specialty",
    source: "Typical building sump or domestic water booster pump.",
    icon: "water",
    action: {
      label: "Check for a stuck float or a leaking non-return valve",
      type: "policy",
      cost: 0,
      savingsFraction: 0.5,
      note: "A pump short-cycling on a failed valve can run thousands of hours it should not.",
    },
  },
  {
    id: "vending_snack",
    label: "Non-refrigerated vending machine",
    keywords: ["snack vending", "snack machine", "candy machine", "non-refrigerated vending"],
    wattsOn: 90,
    wattsStandby: 90,
    wattsLow: 40,
    wattsHigh: 180,
    dutyCycle: 1,
    thermostatic: true,
    group: "specialty",
    source: "Lighting and controller only - no compressor.",
    icon: "vending",
    action: {
      label: "Delamp the display and fit an occupancy controller",
      type: "occupancy",
      cost: 90,
      savingsFraction: 0.7,
      note: "Almost all of this load is a backlit advertising panel in an empty corridor.",
    },
  },
  {
    id: "water_heater",
    label: "Electric water heater",
    keywords: ["water heater", "hot water tank", "immersion heater", "point of use heater"],
    wattsOn: 4500,
    wattsStandby: 4500,
    wattsLow: 1500,
    wattsHigh: 5500,
    dutyCycle: 0.12,
    thermostatic: true,
    group: "specialty",
    source: "Standing losses on a storage water heater; duty cycle reflects reheat only.",
    icon: "heater",
    action: {
      label: "Setback timer and tank insulation",
      type: "timer",
      cost: 70,
      savingsFraction: 0.4,
      note: "A storage tank reheats itself all weekend for a building with nobody in it.",
    },
  },
  {
    id: "elevator",
    label: "Elevator / lift standby",
    keywords: ["elevator", "lift standby", "lift motor"],
    wattsOn: 400,
    wattsStandby: 250,
    wattsLow: 100,
    wattsHigh: 900,
    dutyCycle: 1,
    thermostatic: true,
    group: "specialty",
    source: "Cab lighting, ventilation and controller idling between calls.",
    icon: "server",
    action: {
      label: "Cab lighting and fan auto-off between calls",
      type: "occupancy",
      cost: 150,
      savingsFraction: 0.5,
      note: "The motor is idle overnight but the cab light and fan usually are not.",
    },
  },
];
